insert into country(id_country,name_country) values (1,'Россия');
insert into country(id_country,name_country) values (2,'Абхазия');
insert into country(id_country,name_country) values (3,'Австралия');
insert into country(id_country,name_country) values (4,'Австрия');
insert into country(id_country,name_country) values (5,'Азербайджан');
insert into country(id_country,name_country) values (6,'Албания');
insert into country(id_country,name_country) values (7,'Алжир');
insert into country(id_country,name_country) values (8,'Ангола');
insert into country(id_country,name_country) values (9,'Ангуилья');
insert into country(id_country,name_country) values (10,'Андорра');
insert into country(id_country,name_country) values (11,'Антигуа и Барбуда');
insert into country(id_country,name_country) values (12,'Антильские о-ва');
insert into country(id_country,name_country) values (13,'Аргентина');
insert into country(id_country,name_country) values (14,'Армения');
insert into country(id_country,name_country) values (15,'Арулько');
insert into country(id_country,name_country) values (16,'Афганистан');
insert into country(id_country,name_country) values (17,'Багамские о-ва');
insert into country(id_country,name_country) values (18,'Бангладеш');
insert into country(id_country,name_country) values (19,'Барбадос');
insert into country(id_country,name_country) values (20,'Бахрейн');
insert into country(id_country,name_country) values (21,'Беларусь');
insert into country(id_country,name_country) values (22,'Белиз');
insert into country(id_country,name_country) values (23,'Бельгия');
insert into country(id_country,name_country) values (24,'Бенин');
insert into country(id_country,name_country) values (25,'Бермуды');
insert into country(id_country,name_country) values (26,'Болгария');
insert into country(id_country,name_country) values (27,'Боливия');
insert into country(id_country,name_country) values (28,'Босния/Герцеговина');
insert into country(id_country,name_country) values (29,'Ботсвана');
insert into country(id_country,name_country) values (30,'Бразилия');
insert into country(id_country,name_country) values (31,'Британские Виргинские о-ва');
insert into country(id_country,name_country) values (32,'Бруней');
insert into country(id_country,name_country) values (33,'Буркина Фасо');
insert into country(id_country,name_country) values (34,'Бурунди');
insert into country(id_country,name_country) values (35,'Бутан');
insert into country(id_country,name_country) values (36,'Валлис и Футуна о-ва');
insert into country(id_country,name_country) values (37,'Вануату');
insert into country(id_country,name_country) values (38,'Великобритания');
insert into country(id_country,name_country) values (39,'Венгрия');
insert into country(id_country,name_country) values (40,'Венесуэла');
insert into country(id_country,name_country) values (41,'Восточный Тимор');
insert into country(id_country,name_country) values (42,'Вьетнам');
insert into country(id_country,name_country) values (43,'Габон');
insert into country(id_country,name_country) values (44,'Гаити');
insert into country(id_country,name_country) values (45,'Гайана');
insert into country(id_country,name_country) values (46,'Гамбия');
insert into country(id_country,name_country) values (47,'Гана');
insert into country(id_country,name_country) values (48,'Гваделупа');
insert into country(id_country,name_country) values (49,'Гватемала');
insert into country(id_country,name_country) values (50,'Гвинея');
insert into country(id_country,name_country) values (51,'Гвинея-Бисау');
insert into country(id_country,name_country) values (52,'Германия');
insert into country(id_country,name_country) values (53,'Гернси о-в');
insert into country(id_country,name_country) values (54,'Гибралтар');
insert into country(id_country,name_country) values (55,'Гондурас');
insert into country(id_country,name_country) values (56,'Гонконг');
insert into country(id_country,name_country) values (57,'Гренада');
insert into country(id_country,name_country) values (58,'Гренландия');
insert into country(id_country,name_country) values (59,'Греция');
insert into country(id_country,name_country) values (60,'Грузия');
insert into country(id_country,name_country) values (61,'Дания');
insert into country(id_country,name_country) values (62,'Джерси о-в');
insert into country(id_country,name_country) values (63,'Джибути');
insert into country(id_country,name_country) values (64,'Доминиканская республика');
insert into country(id_country,name_country) values (65,'Египет');
insert into country(id_country,name_country) values (66,'Замбия');
insert into country(id_country,name_country) values (67,'Западная Сахара');
insert into country(id_country,name_country) values (68,'Зимбабве');
insert into country(id_country,name_country) values (69,'Израиль');
insert into country(id_country,name_country) values (70,'Индия');
insert into country(id_country,name_country) values (71,'Индонезия');
insert into country(id_country,name_country) values (72,'Иордания');
insert into country(id_country,name_country) values (73,'Ирак');
insert into country(id_country,name_country) values (74,'Иран');
insert into country(id_country,name_country) values (75,'Ирландия');
insert into country(id_country,name_country) values (76,'Исландия');
insert into country(id_country,name_country) values (77,'Испания');
insert into country(id_country,name_country) values (78,'Италия');
insert into country(id_country,name_country) values (79,'Йемен');
insert into country(id_country,name_country) values (80,'Кабо-Верде');
insert into country(id_country,name_country) values (81,'Казахстан');
insert into country(id_country,name_country) values (82,'Камбоджа');
insert into country(id_country,name_country) values (83,'Камерун');
insert into country(id_country,name_country) values (84,'Канада');
insert into country(id_country,name_country) values (85,'Катар');
insert into country(id_country,name_country) values (86,'Кения');
insert into country(id_country,name_country) values (87,'Кипр');
insert into country(id_country,name_country) values (88,'Кирибати');
insert into country(id_country,name_country) values (89,'Китай');
insert into country(id_country,name_country) values (90,'Колумбия');
insert into country(id_country,name_country) values (91,'Коморские о-ва');
insert into country(id_country,name_country) values (92,'Конго (Brazzaville)');
insert into country(id_country,name_country) values (93,'Конго (Kinshasa)');
insert into country(id_country,name_country) values (94,'Коста-Рика');
insert into country(id_country,name_country) values (95,'Кот-д''''Ивуар');
insert into country(id_country,name_country) values (96,'Куба');
insert into country(id_country,name_country) values (97,'Кувейт');
insert into country(id_country,name_country) values (98,'Кука о-ва');
insert into country(id_country,name_country) values (99,'Кыргызстан');
insert into country(id_country,name_country) values (100,'Лаос');
insert into country(id_country,name_country) values (101,'Латвия');
insert into country(id_country,name_country) values (102,'Лесото');
insert into country(id_country,name_country) values (103,'Либерия');
insert into country(id_country,name_country) values (104,'Ливан');
insert into country(id_country,name_country) values (105,'Ливия');
insert into country(id_country,name_country) values (106,'Литва');
insert into country(id_country,name_country) values (107,'Лихтенштейн');
insert into country(id_country,name_country) values (108,'Люксембург');
insert into country(id_country,name_country) values (109,'Маврикий');
insert into country(id_country,name_country) values (110,'Мавритания');
insert into country(id_country,name_country) values (111,'Мадагаскар');
insert into country(id_country,name_country) values (112,'Македония');
insert into country(id_country,name_country) values (113,'Малави');
insert into country(id_country,name_country) values (114,'Малайзия');
insert into country(id_country,name_country) values (115,'Мали');
insert into country(id_country,name_country) values (116,'Мальдивские о-ва');
insert into country(id_country,name_country) values (117,'Мальта');
insert into country(id_country,name_country) values (118,'Мартиника о-в');
insert into country(id_country,name_country) values (119,'Мексика');
insert into country(id_country,name_country) values (120,'Мозамбик');
insert into country(id_country,name_country) values (121,'Молдова');
insert into country(id_country,name_country) values (122,'Монако');
insert into country(id_country,name_country) values (123,'Монголия');
insert into country(id_country,name_country) values (124,'Марокко');
insert into country(id_country,name_country) values (125,'Мьянма (Бирма)');
insert into country(id_country,name_country) values (126,'Мэн о-в');
insert into country(id_country,name_country) values (127,'Намибия');
insert into country(id_country,name_country) values (128,'Науру');
insert into country(id_country,name_country) values (129,'Непал');
insert into country(id_country,name_country) values (130,'Нигер');
insert into country(id_country,name_country) values (131,'Нигерия');
insert into country(id_country,name_country) values (132,'Нидерланды (Голландия)');
insert into country(id_country,name_country) values (133,'Никарагуа');
insert into country(id_country,name_country) values (134,'Новая Зеландия');
insert into country(id_country,name_country) values (135,'Новая Каледония о-в');
insert into country(id_country,name_country) values (136,'Норвегия');
insert into country(id_country,name_country) values (137,'Норфолк о-в');
insert into country(id_country,name_country) values (138,'О.А.Э.');
insert into country(id_country,name_country) values (139,'Оман');
insert into country(id_country,name_country) values (140,'Пакистан');
insert into country(id_country,name_country) values (141,'Панама');
insert into country(id_country,name_country) values (142,'Папуа Новая Гвинея');
insert into country(id_country,name_country) values (143,'Парагвай');
insert into country(id_country,name_country) values (144,'Перу');
insert into country(id_country,name_country) values (145,'Питкэрн о-в');
insert into country(id_country,name_country) values (146,'Польша');
insert into country(id_country,name_country) values (147,'Португалия');
insert into country(id_country,name_country) values (148,'Пуэрто Рико');
insert into country(id_country,name_country) values (149,'Реюньон');
insert into country(id_country,name_country) values (150,'Руанда');
insert into country(id_country,name_country) values (151,'Румыния');
insert into country(id_country,name_country) values (152,'США');
insert into country(id_country,name_country) values (153,'Сальвадор');
insert into country(id_country,name_country) values (154,'Самоа');
insert into country(id_country,name_country) values (155,'Сан-Марино');
insert into country(id_country,name_country) values (156,'Сан-Томе и Принсипи');
insert into country(id_country,name_country) values (157,'Саудовская Аравия');
insert into country(id_country,name_country) values (158,'Свазиленд');
insert into country(id_country,name_country) values (159,'Святая Люсия');
insert into country(id_country,name_country) values (160,'Святой Елены о-в');
insert into country(id_country,name_country) values (161,'Северная Корея');
insert into country(id_country,name_country) values (162,'Сейшеллы');
insert into country(id_country,name_country) values (163,'Сен-Пьер и Микелон');
insert into country(id_country,name_country) values (164,'Сенегал');
insert into country(id_country,name_country) values (165,'Сент Китс и Невис');
insert into country(id_country,name_country) values (166,'Сент-Винсент и Гренадины');
insert into country(id_country,name_country) values (167,'Сербия');
insert into country(id_country,name_country) values (168,'Сингапур');
insert into country(id_country,name_country) values (169,'Сирия');
insert into country(id_country,name_country) values (170,'Словакия');
insert into country(id_country,name_country) values (171,'Словения');
insert into country(id_country,name_country) values (172,'Соломоновы о-ва');
insert into country(id_country,name_country) values (173,'Сомали');
insert into country(id_country,name_country) values (174,'Судан');
insert into country(id_country,name_country) values (175,'Суринам');
insert into country(id_country,name_country) values (176,'Сьерра-Леоне');
insert into country(id_country,name_country) values (177,'Таджикистан');
insert into country(id_country,name_country) values (178,'Тайвань');
insert into country(id_country,name_country) values (179,'Таиланд');
insert into country(id_country,name_country) values (180,'Танзания');
insert into country(id_country,name_country) values (181,'Того');
insert into country(id_country,name_country) values (182,'Токелау о-ва');
insert into country(id_country,name_country) values (183,'Тонга');
insert into country(id_country,name_country) values (184,'Тринидад и Тобаго');
insert into country(id_country,name_country) values (185,'Тувалу');
insert into country(id_country,name_country) values (186,'Тунис');
insert into country(id_country,name_country) values (187,'Туркменистан');
insert into country(id_country,name_country) values (188,'Туркс и Кейкос');
insert into country(id_country,name_country) values (189,'Турция');
insert into country(id_country,name_country) values (190,'Уганда');
insert into country(id_country,name_country) values (191,'Узбекистан');
insert into country(id_country,name_country) values (192,'Уругвай');
insert into country(id_country,name_country) values (193,'Фарерские о-ва');
insert into country(id_country,name_country) values (194,'Фиджи');
insert into country(id_country,name_country) values (195,'Филиппины');
insert into country(id_country,name_country) values (196,'Финляндия');
insert into country(id_country,name_country) values (197,'Франция');
insert into country(id_country,name_country) values (198,'Французская Гвинея');
insert into country(id_country,name_country) values (199,'Французская Полинезия');
insert into country(id_country,name_country) values (200,'Хорватия');
insert into country(id_country,name_country) values (201,'Чад');
insert into country(id_country,name_country) values (202,'Черногория');
insert into country(id_country,name_country) values (203,'Чехия');
insert into country(id_country,name_country) values (204,'Чили');
insert into country(id_country,name_country) values (205,'Швейцария');
insert into country(id_country,name_country) values (206,'Швеция');
insert into country(id_country,name_country) values (207,'Шри-Ланка');
insert into country(id_country,name_country) values (208,'Эквадор');
insert into country(id_country,name_country) values (209,'Экваториальная Гвинея');
insert into country(id_country,name_country) values (210,'Эритрея');
insert into country(id_country,name_country) values (211,'Эстония');
insert into country(id_country,name_country) values (212,'Эфиопия');
insert into country(id_country,name_country) values (213,'ЮАР');
insert into country(id_country,name_country) values (214,'Южная Корея');
insert into country(id_country,name_country) values (215,'Южная Осетия');
insert into country(id_country,name_country) values (216,'Ямайка');
insert into country(id_country,name_country) values (217,'Япония');
